spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN

server:
  port: 8081

logging:
  level:
    org.hibernate.sq: debug
    org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6