spring:
  jpa:
    show-sql: on
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: user
      password: 1234
      roles: USER
server:
  port: 8081

