spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    open-in-view: false
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN

logging:
  level:
    org.hibernate.sq: debug
    org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}